name: Build
on:
  push:
    branches:
      - "**"

jobs:
  build-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x
      - name: Build check
        run: |
          go build .
      - name: go test
        run: |
          go test -v ./...
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
      - name: Run tmate
        if: failure()
        uses: mxschmitt/action-tmate@v3
